name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      # CHANGEME: Set the filenames of your config files here:
      files: project-template-esp32.yaml,project-template-esp8266.yaml,socket_template.yaml,socket_template2.yaml,ali-socket.yaml
      # CHANGEME: Set the name of your project here:
      name: Template Project
